import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the movie slice
const initialState = {
  currentMovie: {},
};

// Create a slice for movies with `createSlice`
const movieSlice = createSlice({
  name: "movie", // Name of the slice
  initialState: {
    currentMovie: "",
  }, // Initial state
  reducers: {
    // Reducer to set the movie details
    setMovieDetails(state, action) {
      state.currentMovie = action.payload;
    },
    resetMovieDetails: (state) => {
      state.currentMovie = "";
    },
    // You can add more reducers here if needed
  },
});

// Export the action creators generated by createSlice
export const { setMovieDetails, resetMovieDetails } = movieSlice.actions;

// Export the reducer as the default export
export default movieSlice.reducer;
